version: '3.1'

services:

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: escola_ingles
      MARIADB_USER: user_name
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    ports: 
      - "3306:3306"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
